In [1]:
import numpy as np
import pandas as pd
from scipy.stats import zscore

In [2]:
# MLB pitching stats data
sp_pitch_data = pd.read_csv('Resources/2018_2023_mlb_sp_stats.csv')

In [3]:
sp_pitch_data

,Season,Name,Team,Name.1,Team.1,Season.1,Age,W,L,ERA,...,wOppTeamV,wNetPitV,TG,wOBA,OBP,SLG,wSB,NameASCII,PlayerId,MLBAMID
0,2023,Zack Greinke,KCR,Zack Greinke,KCR,2023,39,1,12,5.530121,...,0.221085,0.221085,132,NaN,NaN,NaN,NaN,Zack Greinke,1943,425844
1,2023,Clayton Kershaw,LAD,Clayton Kershaw,LAD,2023,35,11,4,2.515528,...,0.000000,-0.263970,129,NaN,NaN,NaN,NaN,Clayton Kershaw,2036,477132
2,2023,Adam Wainwright,STL,Adam Wainwright,STL,2023,41,3,9,8.612070,...,0.124603,-0.299898,131,NaN,NaN,NaN,NaN,Adam Wainwright,2233,425794
3,2023,Corey Kluber,BOS,Corey Kluber,BOS,2023,37,2,6,6.264000,...,0.000000,0.000000,131,NaN,NaN,NaN,NaN,Corey Kluber,2429,446372
4,2023,Lance Lynn,CHW,Lance Lynn,CHW,2023,36,6,9,6.467967,...,0.262619,0.262619,131,NaN,NaN,NaN,NaN,Lance Lynn,2520,458681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2209,2018,Walker Buehler,LAD,Walker Buehler,LAD,2018,23,8,4,2.310514,...,0.000000,0.000000,163,NaN,NaN,NaN,NaN,Walker Buehler,19374,621111
2210,2018,Shane Bieber,CLE,Shane Bieber,CLE,2018,23,11,4,4.254545,...,0.000000,0.000000,162,NaN,NaN,NaN,NaN,Shane Bieber,19427,669456
2211,2018,Jonathan Loáisiga,NYY,Jonathan Loáisiga,NYY,2018,23,2,0,3.000000,...,0.000000,0.000000,162,NaN,NaN,NaN,NaN,Jonathan Loaisiga,19753,642528
2212,2018,Shohei Ohtani,LAA,Shohei Ohtani,LAA,2018,23,4,2,3.309678,...,0.000000,0.000000,162,NaN,NaN,NaN,NaN,Shohei Ohtani,19755,660271
2213,2018,Bryse Wilson,ATL,Bryse Wilson,ATL,2018,20,1,0,0.000000,...,0.000000,0.000000,162,NaN,NaN,NaN,NaN,Bryse Wilson,19990,669060

In [4]:
# Filter out rows with Season 2020 due to pandemic year (Only 60 games played)
sp_pitch_data = sp_pitch_data[sp_pitch_data['Season'] != 2020]

# Drop the 'Season.1' column.
columns_to_drop = ['Name.1', 'Team.1', 'Season.1', 'NameASCII', 'MLBAMID']

sp_pitch_data = sp_pitch_data.drop(columns= columns_to_drop)

sp_pitch_data.head()

,Season,Name,Team,Age,W,L,ERA,G,GS,CG,...,ESV,wTeamV,wOppTeamV,wNetPitV,TG,wOBA,OBP,SLG,wSB,PlayerId
0,2023,Zack Greinke,KCR,39,1,12,5.530121,22,22,0,...,1.0,0.000000,0.221085,0.221085,132,NaN,NaN,NaN,NaN,1943
1,2023,Clayton Kershaw,LAD,35,11,4,2.515528,19,19,0,...,0.0,-0.263970,0.000000,-0.263970,129,NaN,NaN,NaN,NaN,2036
2,2023,Adam Wainwright,STL,41,3,9,8.612070,17,17,0,...,3.0,-0.424501,0.124603,-0.299898,131,NaN,NaN,NaN,NaN,2233
3,2023,Corey Kluber,BOS,37,2,6,6.264000,9,9,0,...,0.0,0.000000,0.000000,0.000000,131,NaN,NaN,NaN,NaN,2429
4,2023,Lance Lynn,CHW,36,6,9,6.467967,21,21,0,...,2.0,0.000000,0.262619,0.262619,131,NaN,NaN,NaN,NaN,2520

In [5]:
# Fill remaining null values with zeros to account for any gaps in data since pitchers do not all throw the same pitches.
sp_pitch_data = sp_pitch_data.fillna(0)

# Display the cleaned and filled DataFrame
sp_pitch_data.head()

,Season,Name,Team,Age,W,L,ERA,G,GS,CG,...,ESV,wTeamV,wOppTeamV,wNetPitV,TG,wOBA,OBP,SLG,wSB,PlayerId
0,2023,Zack Greinke,KCR,39,1,12,5.530121,22,22,0,...,1.0,0.000000,0.221085,0.221085,132,0.0,0.0,0.0,0.0,1943
1,2023,Clayton Kershaw,LAD,35,11,4,2.515528,19,19,0,...,0.0,-0.263970,0.000000,-0.263970,129,0.0,0.0,0.0,0.0,2036
2,2023,Adam Wainwright,STL,41,3,9,8.612070,17,17,0,...,3.0,-0.424501,0.124603,-0.299898,131,0.0,0.0,0.0,0.0,2233
3,2023,Corey Kluber,BOS,37,2,6,6.264000,9,9,0,...,0.0,0.000000,0.000000,0.000000,131,0.0,0.0,0.0,0.0,2429
4,2023,Lance Lynn,CHW,36,6,9,6.467967,21,21,0,...,2.0,0.000000,0.262619,0.262619,131,0.0,0.0,0.0,0.0,2520

In [6]:
# Filter out columns with (pi) in their titles
columns_to_drop = sp_pitch_data.filter(like="(pi)").columns

# Drop the specified columns
sp_pitch_data = sp_pitch_data.drop(columns=columns_to_drop)

In [7]:
# Filter DF for the relevant seasons (2018, 2019, 2021, 2022)
relevant_seasons = [2018, 2019, 2021, 2022]
filtered_pitching_data = sp_pitch_data[sp_pitch_data['Season'].isin(relevant_seasons)]

# Group the data by player for target 2023
sp_data_2023 = sp_pitch_data[sp_pitch_data['Season'] == 2023]
grouped_data = filtered_pitching_data.groupby('PlayerId')

# Calculate average statistics for ERA, FIP, and WHIP
average_stats = grouped_data[['ERA', 'FIP', 'WHIP']].mean()

# Merge the average stats with the 2023 stats for each player
stats_2023 = pd.merge(average_stats, sp_data_2023[['PlayerId', 'ERA', 'FIP', 'WHIP']], on='PlayerId', suffixes=('_avg', '_2023'))

# Merge pitcher names with the results DF, and merge pitcher names and calculated results
pitcher_output = pd.merge(
   filtered_pitching_data[['PlayerId', 'Name']].drop_duplicates(),
   stats_2023,
   on='PlayerId'
)

# Merging pitcher_output back with sp_pitch_data to retain all columns
merged_data = pd.merge(sp_pitch_data, pitcher_output, on=['PlayerId', 'Name'], how='left')

# Clean up duplicate rows by keeping the first occurrence
merged_data = merged_data.drop_duplicates(subset=['PlayerId', 'Name'], keep='first')

# Display the merged result
merged_data.head()

,Season,Name,Team,Age,W,L,ERA,G,GS,CG,...,OBP,SLG,wSB,PlayerId,ERA_avg,FIP_avg,WHIP_avg,ERA_2023,FIP_2023,WHIP_2023
0,2023,Zack Greinke,KCR,39,1,12,5.530121,22,22,0,...,0.0,0.0,0.0,1943,3.381562,3.780352,1.121997,5.530121,5.141063,1.274096
1,2023,Clayton Kershaw,LAD,35,11,4,2.515528,19,19,0,...,0.0,0.0,0.0,2036,2.902238,3.155674,1.012831,2.515528,3.755054,1.015528
2,2023,Adam Wainwright,STL,41,3,9,8.612070,17,17,0,...,0.0,0.0,0.0,2233,3.854966,3.989132,1.307504,8.612070,6.024892,1.991379
3,2023,Corey Kluber,BOS,37,2,6,6.264000,9,9,0,...,0.0,0.0,0.0,2429,4.213119,3.648284,1.298954,6.264000,6.582582,1.536000
4,2023,Lance Lynn,CHW,36,6,9,6.467967,21,21,0,...,0.0,0.0,0.0,2520,4.011502,3.463603,1.283427,6.467967,5.209300,1.462396

In [8]:
merged_data.to_csv('Resources/merged_data.csv', encoding="utf-8", index=False)

In [9]:
epsilon = 1e-6  # A small constant to avoid zero standard deviation

# Calculate z-scores for ERA, FIP, and WHIP
z_scores_era_avg = zscore(merged_data['ERA_avg'].fillna(0))
z_score_era_2023 = zscore(merged_data['ERA_2023'].fillna(0) + epsilon)
z_scores_fip_avg = zscore(merged_data['FIP_avg'].fillna(0))
z_score_fip_2023 = zscore(merged_data['FIP_2023'].fillna(0) + epsilon)
z_scores_whip_avg = zscore(merged_data['WHIP_avg'].fillna(0))
z_score_whip_2023 = zscore(merged_data['WHIP_2023'].fillna(0) + epsilon)

# Calculate the differences between z-scores
z_score_diff_era = z_score_era_2023 - z_scores_era_avg
z_score_diff_fip = z_score_fip_2023 - z_scores_fip_avg
z_score_diff_whip = z_score_whip_2023 - z_scores_whip_avg

# Add the z-scores and differences as new columns to the DataFrame
merged_data['z_score_era_avg'] = z_scores_era_avg
merged_data['z_score_era_2023'] = z_score_era_2023
merged_data['z_score_diff_era'] = z_score_diff_era
merged_data['z_score_fip_avg'] = z_scores_fip_avg
merged_data['z_score_fip_2023'] = z_score_fip_2023
merged_data['z_score_diff_fip'] = z_score_diff_fip
merged_data['z_score_whip_avg'] = z_scores_whip_avg
merged_data['z_score_whip_2023'] = z_score_whip_2023
merged_data['z_score_diff_whip'] = z_score_diff_whip

# Display the DataFrame
print(merged_data.head())

   Season             Name Team  Age   W   L       ERA   G  GS  CG  ...  \
0    2023     Zack Greinke  KCR   39   1  12  5.530121  22  22   0  ...
1    2023  Clayton Kershaw  LAD   35  11   4  2.515528  19  19   0  ...
2    2023  Adam Wainwright  STL   41   3   9  8.612070  17  17   0  ...
3    2023     Corey Kluber  BOS   37   2   6  6.264000   9   9   0  ...
4    2023       Lance Lynn  CHW   36   6   9  6.467967  21  21   0  ...

   WHIP_2023  z_score_era_avg  z_score_era_2023  z_score_diff_era  \
0   1.274096         0.519061          1.072843          0.553782
1   1.015528         0.380312          0.259911         -0.120401
2   1.991379         0.656097          1.903939          1.247842
3   1.536000         0.759771          1.270745          0.510974
4   1.462396         0.701409          1.325748          0.624339

   z_score_fip_avg  z_score_fip_2023  z_score_diff_fip  z_score_whip_avg  \
0         1.060424          1.306977          0.246553          0.920639
1         0.783668          0.812423          0.028755          0.772453
2         1.152921          1.622344          0.469423          1.172455
3         1.001913          1.821338          0.819426          1.160850
4         0.920092          1.331326          0.411234          1.139772

   z_score_whip_2023  z_score_diff_whip
0           1.045738           0.125098
1           0.718473          -0.053980
2           1.953588           0.781133
3           1.377224           0.216374
4           1.284064           0.144292

[5 rows x 356 columns]

In [10]:
# Check standard deviations
print("Standard Deviations:")
print("ERA_avg:", merged_data['ERA_avg'].std())
print("FIP_avg:", merged_data['FIP_avg'].std())
print("WHIP_avg:", merged_data['WHIP_avg'].std())
print("ERA_2023:", merged_data['ERA_2023'].std())
print("FIP_2023:", merged_data['FIP_2023'].std())
print("WHIP_2023:", merged_data['WHIP_2023'].std())

Standard Deviations:
ERA_avg: 4.520765732635006
FIP_avg: 1.6020815835787197
WHIP_avg: 0.5754009419919922
ERA_2023: 5.21380796289467
FIP_2023: 3.103642706486236
WHIP_2023: 0.7547666035113192

In [11]:

print("Intermediate Values:")
print("z_scores_era_avg:", z_scores_era_avg)
print("z_score_era_2023:", z_score_era_2023)

Intermediate Values:
z_scores_era_avg: 0       0.519061
1       0.380312
2       0.656097
3       0.759771
4       0.701409
          ...
1975   -0.459795
1976   -0.459795
1977   -0.459795
1978   -0.459795
1993   -0.459795
Name: ERA_avg, Length: 842, dtype: float64
z_score_era_2023: 0       1.072843
1       0.259911
2       1.903939
3       1.270745
4       1.325748
          ...
1975   -0.418440
1976   -0.418440
1977   -0.418440
1978   -0.418440
1993   -0.418440
Name: ERA_2023, Length: 842, dtype: float64

In [12]:

print("Intermediate Values:")
print("z_scores_fip_avg:", z_scores_fip_avg)
print("z_score_fip_2023:", z_score_fip_2023)

Intermediate Values:
z_scores_fip_avg: 0       1.060424
1       0.783668
2       1.152921
3       1.001913
4       0.920092
          ...
1975   -0.614415
1976   -0.614415
1977   -0.614415
1978   -0.614415
1993   -0.614415
Name: FIP_avg, Length: 842, dtype: float64
z_score_fip_2023: 0       1.306977
1       0.812423
2       1.622344
3       1.821338
4       1.331326
          ...
1975   -0.527452
1976   -0.527452
1977   -0.527452
1978   -0.527452
1993   -0.527452
Name: FIP_2023, Length: 842, dtype: float64

In [13]:

print("Intermediate Values:")
print("z_scores_whip_avg:", z_scores_whip_avg)
print("z_score_whip_2023:", z_score_whip_2023)

Intermediate Values:
z_scores_whip_avg: 0       0.920639
1       0.772453
2       1.172455
3       1.160850
4       1.139772
          ...
1975   -0.602412
1976   -0.602412
1977   -0.602412
1978   -0.602412
1993   -0.602412
Name: WHIP_avg, Length: 842, dtype: float64
z_score_whip_2023: 0       1.045738
1       0.718473
2       1.953588
3       1.377224
4       1.284064
          ...
1975   -0.566861
1976   -0.566861
1977   -0.566861
1978   -0.566861
1993   -0.566861
Name: WHIP_2023, Length: 842, dtype: float64

In [14]:
#  Output full pitch data to csv
merged_data.to_csv('Resources/full_pitcher_data.csv', encoding="utf-8", index=False)

In [15]:
merged_data.head()

,Season,Name,Team,Age,W,L,ERA,G,GS,CG,...,WHIP_2023,z_score_era_avg,z_score_era_2023,z_score_diff_era,z_score_fip_avg,z_score_fip_2023,z_score_diff_fip,z_score_whip_avg,z_score_whip_2023,z_score_diff_whip
0,2023,Zack Greinke,KCR,39,1,12,5.530121,22,22,0,...,1.274096,0.519061,1.072843,0.553782,1.060424,1.306977,0.246553,0.920639,1.045738,0.125098
1,2023,Clayton Kershaw,LAD,35,11,4,2.515528,19,19,0,...,1.015528,0.380312,0.259911,-0.120401,0.783668,0.812423,0.028755,0.772453,0.718473,-0.053980
2,2023,Adam Wainwright,STL,41,3,9,8.612070,17,17,0,...,1.991379,0.656097,1.903939,1.247842,1.152921,1.622344,0.469423,1.172455,1.953588,0.781133
3,2023,Corey Kluber,BOS,37,2,6,6.264000,9,9,0,...,1.536000,0.759771,1.270745,0.510974,1.001913,1.821338,0.819426,1.160850,1.377224,0.216374
4,2023,Lance Lynn,CHW,36,6,9,6.467967,21,21,0,...,1.462396,0.701409,1.325748,0.624339,0.920092,1.331326,0.411234,1.139772,1.284064,0.144292

In [16]:
# Create dataset for ERA learning
columns_to_drop = ['PlayerId', 'Name', 'ERA_2023', 'FIP_2023', 'WHIP_2023',
                   'z_score_diff_fip', 'z_score_diff_whip']

for_learning_era = merged_data.drop(columns=columns_to_drop)
for_learning_era.head()

,Season,Team,Age,W,L,ERA,G,GS,CG,ShO,...,ERA_avg,FIP_avg,WHIP_avg,z_score_era_avg,z_score_era_2023,z_score_diff_era,z_score_fip_avg,z_score_fip_2023,z_score_whip_avg,z_score_whip_2023
0,2023,KCR,39,1,12,5.530121,22,22,0,0,...,3.381562,3.780352,1.121997,0.519061,1.072843,0.553782,1.060424,1.306977,0.920639,1.045738
1,2023,LAD,35,11,4,2.515528,19,19,0,0,...,2.902238,3.155674,1.012831,0.380312,0.259911,-0.120401,0.783668,0.812423,0.772453,0.718473
2,2023,STL,41,3,9,8.612070,17,17,0,0,...,3.854966,3.989132,1.307504,0.656097,1.903939,1.247842,1.152921,1.622344,1.172455,1.953588
3,2023,BOS,37,2,6,6.264000,9,9,0,0,...,4.213119,3.648284,1.298954,0.759771,1.270745,0.510974,1.001913,1.821338,1.160850,1.377224
4,2023,CHW,36,6,9,6.467967,21,21,0,0,...,4.011502,3.463603,1.283427,0.701409,1.325748,0.624339,0.920092,1.331326,1.139772,1.284064

In [24]:
# Save ERA learning dataset to csv
for_learning_era.to_csv('Resources/full_era_learning.csv', encoding="utf-8", index=False)

In [19]:
# Create dataset for FIP learning
columns_to_drop = ['PlayerId', 'Name', 'ERA_2023', 'FIP_2023', 'WHIP_2023',
                   'z_score_diff_era', 'z_score_diff_whip']

for_learning_fip = merged_data.drop(columns=columns_to_drop)
for_learning_fip.head()

,Season,Team,Age,W,L,ERA,G,GS,CG,ShO,...,ERA_avg,FIP_avg,WHIP_avg,z_score_era_avg,z_score_era_2023,z_score_fip_avg,z_score_fip_2023,z_score_diff_fip,z_score_whip_avg,z_score_whip_2023
0,2023,KCR,39,1,12,5.530121,22,22,0,0,...,3.381562,3.780352,1.121997,0.519061,1.072843,1.060424,1.306977,0.246553,0.920639,1.045738
1,2023,LAD,35,11,4,2.515528,19,19,0,0,...,2.902238,3.155674,1.012831,0.380312,0.259911,0.783668,0.812423,0.028755,0.772453,0.718473
2,2023,STL,41,3,9,8.612070,17,17,0,0,...,3.854966,3.989132,1.307504,0.656097,1.903939,1.152921,1.622344,0.469423,1.172455,1.953588
3,2023,BOS,37,2,6,6.264000,9,9,0,0,...,4.213119,3.648284,1.298954,0.759771,1.270745,1.001913,1.821338,0.819426,1.160850,1.377224
4,2023,CHW,36,6,9,6.467967,21,21,0,0,...,4.011502,3.463603,1.283427,0.701409,1.325748,0.920092,1.331326,0.411234,1.139772,1.284064

In [23]:
# Save FIP learning dataset to csv
for_learning_fip.to_csv('Resources/full_fip_learning.csv', encoding="utf-8", index=False)

In [21]:
# Create dataset for WHIP learning
columns_to_drop = ['PlayerId', 'Name', 'ERA_2023', 'FIP_2023', 'WHIP_2023',
                   'z_score_diff_era', 'z_score_diff_fip']

for_learning_whip = merged_data.drop(columns=columns_to_drop)
for_learning_whip.head()

,Season,Team,Age,W,L,ERA,G,GS,CG,ShO,...,ERA_avg,FIP_avg,WHIP_avg,z_score_era_avg,z_score_era_2023,z_score_fip_avg,z_score_fip_2023,z_score_whip_avg,z_score_whip_2023,z_score_diff_whip
0,2023,KCR,39,1,12,5.530121,22,22,0,0,...,3.381562,3.780352,1.121997,0.519061,1.072843,1.060424,1.306977,0.920639,1.045738,0.125098
1,2023,LAD,35,11,4,2.515528,19,19,0,0,...,2.902238,3.155674,1.012831,0.380312,0.259911,0.783668,0.812423,0.772453,0.718473,-0.053980
2,2023,STL,41,3,9,8.612070,17,17,0,0,...,3.854966,3.989132,1.307504,0.656097,1.903939,1.152921,1.622344,1.172455,1.953588,0.781133
3,2023,BOS,37,2,6,6.264000,9,9,0,0,...,4.213119,3.648284,1.298954,0.759771,1.270745,1.001913,1.821338,1.160850,1.377224,0.216374
4,2023,CHW,36,6,9,6.467967,21,21,0,0,...,4.011502,3.463603,1.283427,0.701409,1.325748,0.920092,1.331326,1.139772,1.284064,0.144292

In [22]:
# Save WHIP learning dataset to csv
for_learning_whip.to_csv('Resources/full_whip_learning.csv', encoding="utf-8", index=False)